(deftheme dao-light
  "A monochromatic theme.")

(custom-theme-set-faces
 'dao-light
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#dfdfdf" :foreground "#101010" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 121 :width normal :foundry "JB" :family "JetBrains Mono"))))
 '(cursor ((t (:background "#000000"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#f0babc"))))
 '(homoglyph ((t (:foreground "#a8cbef"))))
 '(minibuffer-prompt ((t (:foreground "#101010" :background "#dfdfdf"))))
 '(highlight ((t (:background "#cdcdcd" :foreground "#101010"))))
 '(region ((t (:extend t :foreground "#dfdfdf" :background "#101010"))))
 '(shadow ((t (:foreground "#dfdfdf"))))
 '(secondary-selection ((t (:extend t :background "#f0babc"))))
 '(trailing-whitespace ((t (:background "#cccccc"))))
 '(whitespace-line ((t (:background "#cccccc"))))
 '(font-lock-builtin-face ((t (:foreground "#101010"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#545454"))))
 '(font-lock-constant-face ((t (:foreground "#101010" :italic t))))
 '(font-lock-doc-face ((t (:foreground "#545454" :italic t))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-function-name-face ((t (:foreground "#101010" :italic t))))
 '(font-lock-keyword-face ((t (:foreground "#101010"))))
 '(font-lock-negation-char-face ((t (:foreground "#dfdfdf" :background "#101010"))))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#bbb55d"))))
 '(font-lock-string-face ((t (:foreground "#545454"))))
 '(font-lock-type-face ((t (:foreground "#101010"))))
 '(font-lock-variable-name-face ((t (:foreground "#101010"))))
 '(font-lock-warning-face ((t (:foreground "#101010"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:slant italic :underline (:color foreground-color :style line) :foreground "#98d96c" :background "#1c1b21"))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:weight light :background "#2d2c33"))))
 '(header-line ((t (:foreground "#101010"))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width (4 . 4) :color "#101010" :style nil) :inverse-video nil :foreground "#dfdfdf" :background "#101010"))))
 '(mode-line-buffer-id ((t (:foreground "#dfdfdf"))))
 '(mode-line-emphasis ((t (:foreground "#a8cbef"))))
 '(mode-line-highlight ((t (:foreground "#c9c049"))))
 '(mode-line-inactive ((t (:box (:line-width (4 . 4) :color "#1c1b21" :style nil) :inverse-video nil :foreground "#4f525f" :background "#1c1b21"))))
 '(isearch ((t (:foreground "#2d2c33" :background "#c9c049"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:foreground "#d1c0ef" :background "#1c1b21"))))
 '(match ((t (:foreground "#98d96c" :background "#83bc5d"))))
 '(next-error ((t (:inherit (region)))))
 '(org-block ((t (:foreground "#101010" :background "#c8c8c8"))))
 '(org-block-begin-line ((t (:foreground "#101010" :background "#d8d8d8"))))
 '(org-block-end-line ((t (:foreground "#101010" :background "#d8d8d8"))))
 '(org-verbatim ((t (:foreground "#101010" :background "#dfdfdf"))))
 '(org-level-1 ((t (:foreground "#101010" :background "#dfdfdf"))))
 '(org-level-2 ((t (:foreground "#101010" :background "#dfdfdf"))))
 '(org-level-3 ((t (:foreground "#101010" :background "#dfdfdf"))))
 '(org-level-4 ((t (:foreground "#101010" :background "#dfdfdf"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#101010"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#636363"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#101010"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#636363"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#101010"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#636363"))))
 '(query-replace ((t (:inherit (isearch))))))


(provide-theme 'dao-light)
